server:
  port: 8769
spring:
  application:
    name: zuul-server
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
zuul:
  routes:
    api-system:
      path: /api/system/**
      serviceId: service-system
    api-order:
      path: /api/order/**
      serviceId: service-order
    api-logistic:
      path: /api/logistic/**
      serviceId: service-logistic
    api-finance:
      path: /api/finance/**
      serviceId: service-finance