eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8769
spring:
  application:
    name: zuul-server
zuul:
  routes:
    api-main:
      path: /api/main/**
      serviceId: service-main
    api-order:
      path: /api/order/**
      serviceId: service-order
